Hello guys,

I was trying to run the "getting started" example and I am getting this error:
```
Traceback (most recent call last):
  File "/home/karahbit/miniconda2/envs/radical27/lib/python2.7/site-packages/radical/utils/threads.py", line 380, in _run
    if not self.work_cb():
  File "/home/karahbit/miniconda2/envs/radical27/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 1124, in work_cb
    ret = self._cb(topic=topic, msg=m)
  File "/home/karahbit/miniconda2/envs/radical27/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 294, in _state_sub_cb
    if not self._update_pilot(thing, publish=False):
  File "/home/karahbit/miniconda2/envs/radical27/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 335, in _update_pilot
    self._pilots[pid]._update(pilot_dict)
  File "/home/karahbit/miniconda2/envs/radical27/lib/python2.7/site-packages/radical/pilot/compute_pilot.py", line 184, in _update
    else      : cb(self, self.state)
  File "/home/karahbit/miniconda2/envs/radical27/lib/python2.7/site-packages/radical/pilot/compute_pilot.py", line 132, in _default_state_cb
    raise RuntimeError('pilot %s failed - fatal!' % self.uid)
RuntimeError: pilot pilot.0000 failed - fatal!
```
My Python version is 
```
Python 2.7.16 :: Anaconda, Inc.
```
```
python               : 2.7.16
  pythonpath           : 
  virtualenv           : radical27

  radical.pilot        : 0.70.3
  radical.saga         : 0.70.0
  radical.utils        : 0.70.0
```

I have attached two sessions as zip files.
[local_session.zip](https://github.com/radical-cybertools/radical.pilot/files/3464249/local_session.zip)
[radical_sandbox_session.zip](https://github.com/radical-cybertools/radical.pilot/files/3464250/radical_sandbox_session.zip)

